# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digital.gov
new_url: https://workflow.digital.gov
email: jeremy.zilar@gsa.gov
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jeremyzilar

include: ["_pages"]

github_org: "GSA"
github_repo: "digitalgov-workflow"
workflow_org: "GSA"
workflow_repo: "digitalgov.gov"

source_of_truth: "https://demo.digital.gov"

# Build settings
markdown: kramdown
# theme: minima
# plugins:
# #   - jekyll-feed
#   # - jemoji
sass:
  sass_dir: _sass

content_types:
  - id: "news"
    title: "News"
    url: /edit/news/
    api: 'https://demo.digital.gov/posts/index.json'
  - id: "events"
    title: "Events"
    url: /edit/events/
    api: 'https://demo.digital.gov/events/index.json'
  - id: "resources"
    title: "Resources"
    url: /edit/resources/
    api: 'https://demo.digital.gov/resources/index.json'
  - id: "services"
    title: "Services"
    url: /edit/services/
    api: 'https://demo.digital.gov/services/index.json'
  - id: "communities"
    title: "Communities"
    url: /edit/communities/
    api: 'https://demo.digital.gov/communities/index.json'
  - id: "topics"
    title: "Topics"
    url: /edit/topics/
    api: 'https://demo.digital.gov/topics/v1/json/'
  - id: "authors"
    title: "Authors"
    url: /edit/authors/
    api: 'https://demo.digital.gov/authors/v1/json/'
  - id: "promos"
    title: "Promos"
    url: /edit/promos/
    api: 'https://demo.digital.gov/promos/v1/json/'
