# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digital.gov Workflow
new_url: https://workflow.digital.gov
email: jeremy.zilar@gsa.gov
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jeremyzilar

include: ["_pages"]

github_org: "GSA"
github_repo: "digitalgov-workflow"
workflow_org: "GSA"
workflow_repo: "digitalgov.gov"


# Build settings
markdown: kramdown
# theme: minima
# plugins:
# #   - jekyll-feed
#   # - jemoji

jekyll_get:
  - data: posts
    json: 'https://demo.digital.gov/posts/index.json'
  - data: events
    json: 'https://digital.gov/events/index.json'
  - data: services
    json: 'https://digital.gov/services/index.json'
  - data: communities
    json: 'https://digital.gov/communities/index.json'
  - data: resources
    json: 'https://digital.gov/resources/index.json'
  - data: tags
    json: 'https://digital.gov/tag/v1/json/'
  - data: categories
    json: 'https://digital.gov/categories/v1/json/'
  - data: topics
    json: 'https://demo.digital.gov/topics/v1/json/'
