name: Services
id: services
page-title: services
description: a services template
base_field: title
filename_prefix: service_
blocks:
- id: filename
  name: Filename
  type: input
  data_type: data
  txt: ""
- id: slug
  name: Slug
  type: input-hidden
  data_type: data
  txt: ""
- id: time
  name: Time
  type: input-hidden
  data_type: skip
- id: title
  name: Service Name
  type: input
  data_type: string
  txt: "Short, topical, no acronyms."
  comment: "Service name"
- id: summary
  name: Summary
  type: textarea
  data_type: string
  txt: "1-sentence description that does not repeat the title"
- id: source_url
  name: Source Url
  type: input
  data_type: string
  txt: "e.g. https://18f.gsa.gov/2019/04/01/ ..."
  comment: "originally published at the following URL"
- id: source
  name: Source
  type: select
  data_type: data
  txt: "this is more text"
  comment: "Which team published this?\n# Learn about sources at https://workflow.digital.gov/sources"
- id: icon
  name: Icon
  type: input
  data_type: data
  txt: ""
  comment: "Images need to be 200x200px with a transparent background\n# Upload new images to Github in the /static/logos/ folder\n# https://github.com/GSA/digitalgov.gov/tree/master/static/promos/\n# The filename should reflect the name of the product or service (e.g., challenge-gov.png)"
- id: email
  name: Email Address
  type: input
  data_type: data
  txt: "Needs to be an email address!"
- id: topics
  name: Topics
  type: select-multiple
  data_type: data
  txt: "see all topics at https://digital.gov/topics"
  comment: "see all authors at https://digital.gov/authors"
- id: primary_image
  name: Primary Image (for social media)
  type: input
  data_type: string
  txt: "Accepts the image slug without extension, e.g. <code>filename-goes-here</code><br/>Upload images here: URLGOESHERE"
  comment: "Primary Image (for social media)"
- id: weight
  name: Page Weight
  type: select-number
  options:
    - blank
    - 0
  data_type: integer
  txt: "Controls how this page appears across the site<br/>0 == hidden<br/>none == visible"
  comment: "Page weight: controls how this page appears across the site\n# 0 == hidden\n# 1 == visible"
- id: aliases
  name: Redirects
  type: textarea
  data_type: data
  txt: "Redirects: enter the path of the URL that you want redirected to this page</br>Note: add two spaces, a dash, and another space before each path"
  comment: "Redirects: enter the path of the URL that you want redirected to this page"
