name: Sources
id: Sources
page-title: sources
description: a sources template
base_field: name
blocks:
- id: filename
  name: Filename
  type: input-hidden
  data_type: data
  txt: ""
- id: slug
  name: Slug
  type: input-hidden
  data_type: data
  txt: ""
- id: name
  name: Source Name
  type: input
  data_type: string
  txt: "e.g. 18F, HHS Idea Lab"
  comment: "Source Name"
- id: summary
  name: Summary
  type: textarea
  data_type: string
  txt: "A short, 1-sentence description that does not include the source name."
- id: domain
  name: Primary Domain
  type: input
  data_type: string
  txt: "e.g. https://18f.gsa.gov/"
  comment: "Primary Domain — the link to your blog homepage or news feed. (e.g. https://18f.gsa.gov/)\n# Note: We'll automatically add ?dg to the end of your URL, to help you track links back to your site."
- id: logo
  name: Source Logo
  type: input
  data_type: string
  txt: Images must be uploaded in the /static/logos/ folder before they can be used here. See https://github.com/GSA/digitalgov.gov/wiki/Sources-on-Digital.gov for more info.
  comment: "Images need to be 200x200px with a transparent background\n# Upload new images to Github in the /static/logos/ folder\n# https://github.com/GSA/digitalgov.gov/tree/main/static/source/ \n# The name of your organization should be clearly reflected in the filename (e.g., usds-logo.png or 18f-logo.png)"
- id: topics
  name: Topics
  type: select-multiple
  data_type: data
  txt: "See all topics at https://digital.gov/topics"
  comment: "see all topics at https://digital.gov/topics"
